apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-media-dev
  labels:
    app: node-media-dev
  namespace: dev
spec:
  selector:
    matchLabels:
      app: node-media-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: node-media-dev
    spec:
      containers:
      - name: node-media-dev
        image: 028621403234.dkr.ecr.us-west-2.amazonaws.com/node-media-server-dev:latest
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: SEGMENT_LENGTH
          value: "1"
        - name: THUMBNAIL_SEGMENT
          value: "0"
        - name: TIMEOUT_TO_CLEANUP
          value: "30000"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: node-media-dev
  labels:
    app: node-media-dev
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: rtmp
    port: 1935
    targetPort: 1935
  selector:
    app: node-media-dev
