apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-media-prod
  labels:
    app: node-media-prod
  namespace: prod
spec:
  selector:
    matchLabels:
      app: node-media-prod
  replicas: 8
  template:
    metadata:
      labels:
        app: node-media-prod
    spec:
      containers:
      - name: node-media-prod
        image: 028621403234.dkr.ecr.us-west-2.amazonaws.com/node-media-server-prod:latest
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: ENV
          value: PRODUCTION
        - name: SEGMENT_LENGTH
          value: "1"
        - name: THUMBNAIL_SEGMENT
          value: "0"
        - name: TIMEOUT_TO_CLEANUP
          value: "30000"
        ports:
        - containerPort: 8000
        readinessProbe:
          tcpSocket:
             port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: node-media-prod
  labels:
    app: node-media-prod
  namespace: prod
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: rtmp
    port: 1935
    targetPort: 1935
  selector:
    app: node-media-prod
